var a = 33;
var b = 10;
var firstname;
firstname = " Abdullah";
document.write(firstname);
var lastname;
lastname = " Al Mamun";
document.write(lastname);
var linebreak;
linebreak = " <br />";
document.write(linebreak);
var age;
age = 24;
document.write("Age: ");
document.write(age);
document.write(linebreak);
result = a + b;
document.write(" Sum: ");
document.write(result);
document.write(linebreak);
result = a - b;
document.write(" Abst: ");
document.write(result);
document.write(linebreak);
result = a * b;
document.write(" Multi: ");
document.write(result);
document.write(linebreak);
result = a / b;
document.write(" Div: ");
document.write(result);
document.write(linebreak);
result = a % b;
document.write(" Mode: ");
document.write(result);
document.write(linebreak);
x = 5 + "5";
document.write(" x= ");
document.write(x);
document.write(linebreak);
document.write(
  " Hello World! Hello Bangladesh ! \
Hello Sirajganj"
);
document.write(" <br />");
document.write('We are so-called "Vikings" from the north');
document.write(linebreak);
var txt = ' We are so-called "Vikings" from the north.';
document.write(txt);
document.write(linebreak);
